// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://nhdmgiyoienkixokcoue.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im5oZG1naXlvaWVua2l4b2tjb3VlIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjA3NzQyNjYsImV4cCI6MjA3NjM1MDI2Nn0.vhTNEb6RR3A8_yMD5R4cjpKAeu2AX6O-xdV_Eb32CNI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});